title: "Zachary Fetters"
author:
  name: "Zachary Fetters"
  email: "hi@zach.fetters.me"
timezone: "America/New_York"
url: https://zach.fetters.me
plugins:
  - jekyll-paginate-v2
gems: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 20
  permalink: /page/:num/
  sort_field: "date"
  title: ":title"
  sort_reverse: true
  trail:
    before: 1
    after: 1

collections:
  posts:
    output             : true
    relative_directory : _posts
    label              : "posts"

future              : true
safe                : false
include             : [".htaccess", "_pages/"]
exclude             : [
                        "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", 
                        "vendor/cache/", "vendor/gems/", "vendor/ruby/", "LICENSE",
                        "README.md", "package.json", "package-lock.json"
                      ]

markdown            : kramdown
highlighter         : rouge
kramdown:
  auto_ids: false
  gfm_emojis: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: "_pages/"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"
  - scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:categories/:year/:title/"
