title: "Zachary Fetters"
author:
  name: "Zachary Fetters"
  email: "hi@zach.fetters.me"
timezone: "America/New_York"

collections:
  posts:
    output             : true
    relative_directory : _posts
    label              : "posts"

safe                : true
include             : [".htaccess", "_pages/"]
exclude             : [
                        "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", 
                        "vendor/cache/", "vendor/gems/", "vendor/ruby/", "LICENSE",
                        "README.md", "package.json", "package-lock.json"
                      ]

defaults:
  - scope:
      path: "_pages/"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"
  - scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
      permalink: /:categories/:year/:i_month/:i_day/:title/