title: "Zachary Fetters"
description: "Photography / Design / Development"
author:
  name: "Zachary Fetters"
  email: "zach@fetters.me"
timezone: "America/New_York"
url: https://zach.fetters.me

future              : true
safe                : false
include             : [".htaccess", "_pages/", ".well-known/"]
exclude             : [
                        "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", 
                        "vendor/cache/", "vendor/gems/", "vendor/ruby/", "LICENSE",
                        "README.md", "package.json", "package-lock.json"
                      ]

markdown            : kramdown
highlighter         : rouge

defaults:
  - scope:
      path: "_pages/"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"