local_backend: false

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "New {{collection}} - {{slug}}"
    update: "Edited {{slug}} in {{collection}}"
    delete: "Removed {{slug}} in {{collection}}"
    uploadMedia: "Uploaded new media - {{path}}"
    deleteMedia: "Removed media - {{path}}"
    openAuthoring: "{{message}} - {{author-name}}"

site_url: "https://zach.fetters.me"
logo_url: "/assets/image/cms-logo.svg"
locale: "en"
show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"