local_backend: false

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "New {{collection}} - {{slug}}"
    update: "Edited {{slug}} in {{collection}}"
    delete: "Removed {{slug}} in {{collection}}"
    uploadMedia: "Uploaded new media - {{path}}"
    deleteMedia: "Removed media - {{path}}"
    openAuthoring: "{{message}} - {{author-name}}"

site_url: "https://zach.fetters.me"
locale: "en"
show_preview_links: false

media_library:
  name: cloudinary
  config:
    cloud_name: attkzach
    api_key: 884321435133287
    use_transformations: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "post"
    label: "Blog"
    label_singular: "Post"
    sortable_fields: ["title", "commit_date", "subtitle", "tags", "commit_author"]
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Category", name: "categories", widget: "select", options: ["technology","programming","photography","art","gaming","design","miscellaneous","meta"] }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", picker_utc: true }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", default: "" }
      - { label: "Cover Image", name: "cover", widget: "image", allow_multiple: false }
      - { label: "Tags", name: "tags", widget: "list", max: 5, min: 0, default: null }
      - { label: "Published?", name: "published", widget: boolean, default: true }
      - { label: "Body Text", name: "body", widget: "markdown" }
  - name: "page"
    label: "Pages"
    label_singular: "Page"
    sortable_fields: ["title", "date", "commit_author", "commit_date"]
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Show in header?", name: "header", widget: "boolean" }
      - { label: "Order in header", name: "order", widget: number, default: null }
      - { label: "Permalink", name: "permalink", widget: "string", default: null }
      - { label: "Custom CSS", name: "stylesheets", widget: "list", default: null }
      - { label: "Custom JS", name: "scripts", widget: "list", default: null }
      - { label: "Body Text", name: "body", widget: "markdown" }